### ISSUE TITLE
LSOA / TTWA match needs (2011) removing from LSOAs

### ISSUE THREAD

**Issue by DanOlner** [life-at-the-frontier/detect-uk-frontiers#5]
LSOA output has ttwa lookup but all end with " (2011)". If I remove those, match with TTWA file is perfect:

lsoa$ttwa <- gsub(x = lsoa$ttwa, pattern = " (2011)", replacement = "", fixed = T)
table(ttwa$ttwa11nm %in% lsoa$ttwa)

TRUE 
 164

**Comment by MengLeZhang** [comment]
sorted. it was an intentional change by me (i.e. adding in 2011). removed it and should now just be ttwa code
