### ISSUE TITLE
Frontiers list isn't lon lat

### ISSUE THREAD

**Issue by DanOlner** [life-at-the-frontier/detect-uk-frontiers#6]
The exported frontiers list (MUCH faster to subset in shiny!) isn't in lon lat, each element is still BNG. (Happy to convert on shiny app end and save there if you don't want to change this.)
Am just doing this in dataprep.R. Is.null test because Penzance doesn't have any frontiers it seems, so there's no data in there.

frontiers.lonlat <- lapply(frontiers, function(x) {
  if(!is.null(x)) st_transform(x, "EPSG:4326")
  })

**Comment by MengLeZhang** [comment]
Resolved long lat issue. Penzance is still a ongoing issue I haven't looked into ...
